import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  WidthType, AlignmentType, HeadingLevel, BorderStyle,
  PageBreak, ShadingType, Header, Footer, PageNumber,
} from 'docx';
import { saveAs } from 'file-saver';

const ACCENT_HEX = 'E87B35';
const DARK_HEX = '1E1E1E';
const GRAY_HEX = '787878';
const LIGHT_BG = 'F8F8F8';
const WHITE = 'FFFFFF';

function monthLabel(month) {
  const [y, m] = month.split('-');
  const months = ['', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];
  return `${months[parseInt(m)]} ${y}`;
}

function fmtNum(n) {
  if (n == null || isNaN(n)) return '—';
  return Number(n).toLocaleString('en-KE', { maximumFractionDigits: 2 });
}

function fmtCurrency(n) {
  if (n == null || isNaN(n)) return '—';
  return 'KES ' + Number(n).toLocaleString('en-KE', { maximumFractionDigits: 0 });
}

function heading(text, level = HeadingLevel.HEADING_1) {
  return new Paragraph({ heading: level, children: [new TextRun({ text, bold: true, color: ACCENT_HEX })] });
}

function bodyText(text) {
  if (!text) return new Paragraph({ children: [new TextRun({ text: '—', color: GRAY_HEX, italics: true })] });
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text, size: 22, color: DARK_HEX })],
  });
}

function labelValue(label, value) {
  return new Paragraph({
    spacing: { after: 60 },
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 20, color: GRAY_HEX }),
      new TextRun({ text: String(value || '—'), size: 22, color: DARK_HEX }),
    ],
  });
}

function makeCell(text, opts = {}) {
  return new TableCell({
    width: opts.width ? { size: opts.width, type: WidthType.DXA } : undefined,
    shading: opts.shading ? { fill: opts.shading, type: ShadingType.CLEAR } : undefined,
    children: [new Paragraph({
      children: [new TextRun({
        text: String(text ?? '—'),
        bold: opts.bold || false,
        size: opts.size || 18,
        color: opts.color || DARK_HEX,
      })],
      alignment: opts.align || AlignmentType.LEFT,
    })],
  });
}

function headerCell(text, width) {
  return makeCell(text, { bold: true, color: WHITE, shading: ACCENT_HEX, width, size: 18 });
}

function makeTable(headers, rows, colWidths) {
  const totalWidth = 9000;
  const widths = colWidths || headers.map(() => Math.floor(totalWidth / headers.length));

  return new Table({
    width: { size: totalWidth, type: WidthType.DXA },
    columnWidths: widths,
    rows: [
      new TableRow({ children: headers.map((h, i) => headerCell(h, widths[i])), tableHeader: true }),
      ...rows.map((row, ri) =>
        new TableRow({
          children: row.map((cell, ci) => makeCell(cell, {
            width: widths[ci],
            shading: ri % 2 === 1 ? LIGHT_BG : undefined,
          })),
        })
      ),
    ],
  });
}

function kvTable(pairs) {
  return makeTable(
    ['Parameter', 'Value'],
    pairs,
    [3500, 5500]
  );
}

function spacer() {
  return new Paragraph({ spacing: { after: 200 }, children: [] });
}

export async function generateMonthlyDocx(data) {
  const p = data.project;
  const label = monthLabel(data.month);

  const sections = [];

  // ═══════════════════════════════════════
  // COVER PAGE
  // ═══════════════════════════════════════
  const coverChildren = [
    new Paragraph({ spacing: { before: 2000 }, children: [] }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: 'MONTHLY PROGRESS REPORT', bold: true, size: 48, color: ACCENT_HEX })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [new TextRun({ text: label, size: 32, color: GRAY_HEX })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
      children: [new TextRun({ text: p.name || 'Project', bold: true, size: 36, color: DARK_HEX })],
    }),
    labelValue('Contract No.', p.contract_number),
    labelValue('Employer', p.employer || 'Kenya National Highways Authority (KeNHA)'),
    labelValue('Engineer', p.consultant || '—'),
    labelValue('Contractor', p.contractor || '—'),
    labelValue('Contract Sum', fmtCurrency(data.financial.contractSum)),
    labelValue('Commencement Date', p.start_date || '—'),
    labelValue('Completion Date', p.end_date || '—'),
    labelValue('FIDIC Edition', p.fidic_edition || 'Red Book 1999'),
    labelValue('Report Period', `${data.startDate} to ${data.endDate}`),
    spacer(),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: 'Generated by RoadSite Reports', italics: true, size: 18, color: GRAY_HEX })],
    }),
  ];

  // ═══════════════════════════════════════
  // CONTENT
  // ═══════════════════════════════════════
  const contentChildren = [];

  // 1. Executive Summary
  contentChildren.push(
    heading('1. Executive Summary'),
    bodyText(data.narrative.executive_summary || 'No executive summary provided. Please add via the Monthly Report editor.'),
    spacer(),
  );

  // 2. Physical Progress
  contentChildren.push(
    heading('2. Physical Progress'),
    bodyText(data.narrative.physical_progress_narrative || `Overall physical progress: ${data.physical.overallProgress}%. ${data.physical.monthWorks.length} activities progressed.`),
  );
  if (data.physical.monthWorks.length > 0) {
    contentChildren.push(
      makeTable(
        ['Activity', 'Code', 'Unit', 'This Month', 'Planned Total'],
        data.physical.monthWorks.map(w => [w.activity_name, w.activity_code, w.unit, fmtNum(w.month_qty), fmtNum(w.planned)]),
        [3000, 1200, 800, 1500, 1500]
      ),
    );
  }
  contentChildren.push(spacer());

  // 3. Financial Progress
  contentChildren.push(
    heading('3. Financial Progress'),
    bodyText(data.narrative.financial_progress_narrative || `Financial progress: ${data.financial.financialProgress}%. Certified: ${fmtCurrency(data.financial.totalCertified)}. Paid: ${fmtCurrency(data.financial.totalPaid)}.`),
  );
  if (data.financial.ipcs.length > 0) {
    contentChildren.push(
      makeTable(
        ['IPC No.', 'Certified (KES)', 'Paid (KES)', 'Status'],
        data.financial.ipcs.map(c => [c.ipc_number, fmtNum(c.certified_amount), fmtNum(c.paid_amount), c.status || '—']),
        [1500, 2500, 2500, 2000]
      ),
    );
  }
  contentChildren.push(spacer());

  // 4. Weather
  contentChildren.push(
    heading('4. Weather & Working Days'),
    kvTable([
      ['Total Calendar Days', String(data.weather.workingDays + data.weather.nonWorkingDays)],
      ['Working Days', String(data.weather.workingDays)],
      ['Non-Working Days', String(data.weather.nonWorkingDays)],
      ['Rain Days', String(data.weather.rainDays)],
      ['Average Max Temperature', `${data.weather.avgTemp} °C`],
      ['Total Rainfall', `${data.weather.totalRainfall.toFixed(1)} mm`],
    ]),
    spacer(),
  );

  // 5. Labour
  contentChildren.push(
    heading('5. Manpower & Labour'),
    kvTable([
      ['Total Labour-Days', fmtNum(data.labour.totalLabourDays)],
      ['Average Daily Labour', String(data.labour.avgDailyLabour)],
      ['Peak Labour (single day)', String(data.labour.peakLabour)],
    ]),
    spacer(),
  );

  // 6. Equipment
  contentChildren.push(heading('6. Equipment Utilisation'));
  if (data.equipment.equipUtil.length > 0) {
    contentChildren.push(
      makeTable(
        ['Equipment', 'Type', 'Hours', 'Working', 'Idle', 'Breakdown'],
        data.equipment.equipUtil.map(e => [e.name, e.type, fmtNum(e.total_hours), String(e.working_days), String(e.idle_days), String(e.breakdown_days)]),
        [2500, 1500, 1200, 1200, 1200, 1200]
      ),
    );
  } else {
    contentChildren.push(bodyText('No equipment data recorded.'));
  }
  contentChildren.push(spacer());

  // 7. Quality
  contentChildren.push(
    heading('7. Quality & Testing'),
    bodyText(data.narrative.quality_narrative || `${data.quality.qualityTests.length} tests conducted. Pass rate: ${data.quality.passRate}%.`),
    kvTable([
      ['Total Tests', String(data.quality.qualityTests.length)],
      ['Passed', String(data.quality.testsPassed)],
      ['Failed', String(data.quality.testsFailed)],
      ['Pending', String(data.quality.testsPending)],
      ['Pass Rate', `${data.quality.passRate}%`],
    ]),
    spacer(),
  );

  // 8. Materials
  contentChildren.push(heading('8. Materials Received'));
  if (data.materials.length > 0) {
    contentChildren.push(
      makeTable(
        ['Material', 'Quantity', 'Unit', 'Source', 'Date'],
        data.materials.map(m => [m.material_type, fmtNum(m.quantity), m.unit, m.source || '—', m.received_date]),
        [2000, 1500, 1000, 2500, 1500]
      ),
    );
  } else {
    contentChildren.push(bodyText('No materials received.'));
  }
  contentChildren.push(spacer());

  // 9. Structures
  contentChildren.push(heading('9. Structures Progress'));
  if (data.structures.structProgress.length > 0) {
    contentChildren.push(
      makeTable(
        ['Structure', 'Type', 'Stage', 'Status'],
        data.structures.structProgress.map(s => [
          s.structure?.structure_ref || '—', s.structure?.structure_type || '—', s.stage, s.status
        ]),
        [2000, 2000, 2500, 2000]
      ),
    );
  } else {
    contentChildren.push(bodyText('No structures progress recorded.'));
  }
  contentChildren.push(spacer());

  // 10. Issues
  contentChildren.push(
    heading('10. Site Issues'),
    kvTable([
      ['Issues Raised', String(data.issues.issues.length)],
      ['Open', String(data.issues.issuesOpened)],
      ['Closed / Resolved', String(data.issues.issuesClosed)],
      ['Critical / High', String(data.issues.criticalIssues)],
    ]),
    spacer(),
  );

  // 11. Instructions
  contentChildren.push(heading('11. Site Instructions'));
  if (data.instructions.length > 0) {
    contentChildren.push(
      makeTable(
        ['SI No.', 'Type', 'Subject', 'Status'],
        data.instructions.map(si => [si.instruction_no, si.instruction_type?.replace(/_/g, ' '), si.subject, si.status]),
        [1500, 2000, 3500, 1500]
      ),
    );
  } else {
    contentChildren.push(bodyText('No instructions issued.'));
  }
  contentChildren.push(spacer());

  // 12. Variation Orders
  contentChildren.push(heading('12. Variation Orders'));
  if (data.variationOrders.variationOrders.length > 0) {
    contentChildren.push(
      makeTable(
        ['VO No.', 'Title', 'Amount (KES)', 'Time (days)', 'Status'],
        data.variationOrders.variationOrders.map(v => [
          v.vo_number, v.title, fmtNum(v.approved_amount || v.estimated_amount), String(v.time_impact_days), v.status
        ]),
        [1200, 3000, 2000, 1200, 1500]
      ),
      bodyText(`Total VO value: ${fmtCurrency(data.variationOrders.totalVOAmount)}`),
    );
  } else {
    contentChildren.push(bodyText('No variation orders on record.'));
  }
  contentChildren.push(spacer());

  // 13. H&S
  contentChildren.push(
    heading('13. Health & Safety'),
    bodyText(data.narrative.hse_narrative || `${data.safety.safetyIncidents.length} incidents. LTIs: ${data.safety.ltiCount}. Days lost: ${data.safety.totalDaysLost}.`),
    kvTable([
      ['Total Incidents', String(data.safety.safetyIncidents.length)],
      ['Near Misses', String(data.safety.nearMisses)],
      ['LTIs', String(data.safety.ltiCount)],
      ['Days Lost', String(data.safety.totalDaysLost)],
    ]),
    spacer(),
  );

  // 14. Photos
  contentChildren.push(
    heading('14. Site Photographs'),
    bodyText(`${data.photos.length} photographs captured during the reporting period.`),
    spacer(),
  );

  // 15. Upcoming
  contentChildren.push(
    heading('15. Programme for Next Month'),
    bodyText(data.narrative.upcoming_month_plan || 'No forward plan provided.'),
    spacer(),
  );

  // 16. Recommendations
  contentChildren.push(
    heading('16. Critical Issues & Recommendations'),
    bodyText(data.narrative.critical_issues || 'No critical issues flagged.'),
  );
  if (data.narrative.recommendations) {
    contentChildren.push(
      new Paragraph({ children: [new TextRun({ text: 'Recommendations:', bold: true, size: 22 })] }),
      bodyText(data.narrative.recommendations),
    );
  }

  // ═══════════════════════════════════════
  // BUILD DOCUMENT
  // ═══════════════════════════════════════
  const doc = new Document({
    styles: {
      default: {
        document: { run: { font: 'Calibri', size: 22, color: DARK_HEX } },
      },
    },
    sections: [
      {
        properties: {},
        headers: {
          default: new Header({
            children: [new Paragraph({
              alignment: AlignmentType.RIGHT,
              children: [new TextRun({ text: `${p.name} — ${label}`, size: 16, color: GRAY_HEX, italics: true })],
            })],
          }),
        },
        footers: {
          default: new Footer({
            children: [new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({ text: 'RoadSite Reports  |  Page ', size: 16, color: GRAY_HEX }),
                new TextRun({ children: [PageNumber.CURRENT], size: 16, color: GRAY_HEX }),
                new TextRun({ text: ' of ', size: 16, color: GRAY_HEX }),
                new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: GRAY_HEX }),
              ],
            })],
          }),
        },
        children: [...coverChildren, new Paragraph({ children: [new PageBreak()] }), ...contentChildren],
      },
    ],
  });

  // Generate and download
  const blob = await Packer.toBlob(doc);
  const fileName = `Monthly_Report_${p.name?.replace(/\s+/g, '_')}_${data.month}.docx`;
  saveAs(blob, fileName);
  return fileName;
}
