import jsPDF from 'jspdf';
import 'jspdf-autotable';

const ACCENT = [232, 123, 53]; // KeNHA orange
const DARK = [30, 30, 30];
const GRAY = [120, 120, 120];
const LIGHT_BG = [248, 248, 248];

function monthLabel(month) {
  const [y, m] = month.split('-');
  const months = ['', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];
  return `${months[parseInt(m)]} ${y}`;
}

function fmtNum(n) {
  if (n == null || isNaN(n)) return '—';
  return Number(n).toLocaleString('en-KE', { maximumFractionDigits: 2 });
}

function fmtCurrency(n) {
  if (n == null || isNaN(n)) return '—';
  return 'KES ' + Number(n).toLocaleString('en-KE', { maximumFractionDigits: 0 });
}

export function generateMonthlyPDF(data) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = margin;
  const p = data.project;
  const label = monthLabel(data.month);

  function addPageFooter() {
    const pg = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pg; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(...GRAY);
      doc.text(`RoadSite Reports — ${p.name} — ${label}`, margin, pageH - 8);
      doc.text(`Page ${i} of ${pg}`, pageW - margin, pageH - 8, { align: 'right' });
    }
  }

  function checkPage(need = 30) {
    if (y + need > pageH - 20) {
      doc.addPage();
      y = margin;
    }
  }

  function sectionTitle(title, num) {
    checkPage(20);
    y += 4;
    doc.setFillColor(...ACCENT);
    doc.rect(margin, y, contentW, 8, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(`${num}. ${title}`, margin + 3, y + 5.5);
    y += 13;
    doc.setTextColor(...DARK);
    doc.setFont('helvetica', 'normal');
  }

  function addText(text, size = 10) {
    if (!text) return;
    checkPage(15);
    doc.setFontSize(size);
    doc.setTextColor(...DARK);
    const lines = doc.splitTextToSize(text, contentW);
    doc.text(lines, margin, y);
    y += lines.length * (size * 0.4) + 4;
  }

  function addLabel(label, value) {
    checkPage(10);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...GRAY);
    doc.text(label + ':', margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...DARK);
    doc.text(String(value || '—'), margin + 45, y);
    y += 5;
  }

  function addTable(headers, rows, options = {}) {
    checkPage(25);
    doc.autoTable({
      startY: y,
      head: [headers],
      body: rows,
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 2, textColor: DARK, lineColor: [200, 200, 200], lineWidth: 0.2 },
      headStyles: { fillColor: ACCENT, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
      alternateRowStyles: { fillColor: LIGHT_BG },
      ...options,
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ═══════════════════════════════════════
  // COVER PAGE
  // ═══════════════════════════════════════
  doc.setFillColor(...ACCENT);
  doc.rect(0, 0, pageW, 60, 'F');
  
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('Monthly Progress Report', pageW / 2, 25, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(label, pageW / 2, 38, { align: 'center' });

  doc.setFontSize(8);
  doc.text('Generated by RoadSite Reports', pageW / 2, 50, { align: 'center' });

  y = 75;
  doc.setTextColor(...DARK);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(p.name || 'Project', pageW / 2, y, { align: 'center' });
  y += 12;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const coverFields = [
    ['Contract No.', p.contract_number],
    ['Employer', p.employer || 'Kenya National Highways Authority (KeNHA)'],
    ['Engineer', p.consultant || '—'],
    ['Contractor', p.contractor || '—'],
    ['Contract Sum', fmtCurrency(data.financial.contractSum)],
    ['Commencement Date', p.start_date || '—'],
    ['Completion Date', p.end_date || '—'],
    ['Contract Duration', p.start_date && p.end_date ? `${Math.round((new Date(p.end_date) - new Date(p.start_date)) / 86400000)} days` : '—'],
    ['FIDIC Edition', p.fidic_edition || 'Red Book 1999'],
    ['Project Category', p.category || '—'],
    ['Report Period', `${data.startDate} to ${data.endDate}`],
  ];
  coverFields.forEach(([k, v]) => {
    addLabel(k, v);
  });

  // Key metrics box
  y += 8;
  doc.setFillColor(245, 245, 245);
  doc.roundedRect(margin, y, contentW, 28, 3, 3, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  const metrics = [
    { label: 'Physical Progress', value: `${data.physical.overallProgress}%` },
    { label: 'Financial Progress', value: `${data.financial.financialProgress}%` },
    { label: 'Working Days', value: `${data.weather.workingDays}` },
    { label: 'Avg Labour', value: `${data.labour.avgDailyLabour}` },
  ];
  const mw = contentW / metrics.length;
  metrics.forEach((m, i) => {
    const mx = margin + i * mw + mw / 2;
    doc.setTextColor(...ACCENT);
    doc.setFontSize(14);
    doc.text(m.value, mx, y + 12, { align: 'center' });
    doc.setTextColor(...GRAY);
    doc.setFontSize(7);
    doc.text(m.label, mx, y + 19, { align: 'center' });
  });

  // ═══════════════════════════════════════
  // CONTENT PAGES
  // ═══════════════════════════════════════
  doc.addPage();
  y = margin;

  // 1. EXECUTIVE SUMMARY
  sectionTitle('Executive Summary', 1);
  addText(data.narrative.executive_summary || 'No executive summary provided for this month. Please add narrative via the Monthly Report editor.');

  // 2. PHYSICAL PROGRESS
  sectionTitle('Physical Progress', 2);
  addText(data.narrative.physical_progress_narrative || `Overall physical progress stands at ${data.physical.overallProgress}%. A total of ${data.physical.monthWorks.length} activities were progressed during the month.`);
  
  if (data.physical.monthWorks.length > 0) {
    addTable(
      ['Activity', 'Code', 'Unit', 'This Month', 'Planned Total'],
      data.physical.monthWorks.map(w => [
        w.activity_name, w.activity_code, w.unit, fmtNum(w.month_qty), fmtNum(w.planned)
      ])
    );
  }

  // 3. FINANCIAL PROGRESS
  sectionTitle('Financial Progress', 3);
  addText(data.narrative.financial_progress_narrative || `Financial progress is at ${data.financial.financialProgress}%. Total certified to date: ${fmtCurrency(data.financial.totalCertified)}. Total paid to date: ${fmtCurrency(data.financial.totalPaid)}.`);
  
  if (data.financial.ipcs.length > 0) {
    addTable(
      ['IPC No.', 'Period', 'Certified (KES)', 'Paid (KES)', 'Status'],
      data.financial.ipcs.map(c => [
        c.ipc_number, c.period || '—', fmtNum(c.certified_amount), fmtNum(c.paid_amount), c.status || '—'
      ])
    );
  }

  // 4. WEATHER & WORKING DAYS
  sectionTitle('Weather & Working Days', 4);
  addTable(
    ['Parameter', 'Value'],
    [
      ['Total Calendar Days', data.weather.workingDays + data.weather.nonWorkingDays],
      ['Working Days', data.weather.workingDays],
      ['Non-Working Days', data.weather.nonWorkingDays],
      ['Rain Days', data.weather.rainDays],
      ['Average Max Temperature', `${data.weather.avgTemp} °C`],
      ['Total Rainfall', `${data.weather.totalRainfall.toFixed(1)} mm`],
    ],
    { columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } } }
  );

  // 5. LABOUR
  sectionTitle('Manpower & Labour', 5);
  addTable(
    ['Parameter', 'Value'],
    [
      ['Total Labour-Days', fmtNum(data.labour.totalLabourDays)],
      ['Average Daily Labour', data.labour.avgDailyLabour],
      ['Peak Labour (single day)', data.labour.peakLabour],
    ],
    { columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } } }
  );

  // 6. EQUIPMENT
  sectionTitle('Equipment Utilisation', 6);
  if (data.equipment.equipUtil.length > 0) {
    addTable(
      ['Equipment', 'Type', 'Hours', 'Working Days', 'Idle Days', 'Breakdown Days'],
      data.equipment.equipUtil.map(e => [
        e.name, e.type, fmtNum(e.total_hours), e.working_days, e.idle_days, e.breakdown_days
      ])
    );
  } else {
    addText('No equipment data recorded for this month.');
  }

  // 7. QUALITY TESTS
  sectionTitle('Quality & Testing', 7);
  addText(data.narrative.quality_narrative || `A total of ${data.quality.qualityTests.length} tests were conducted. Pass rate: ${data.quality.passRate}%.`);
  addTable(
    ['Parameter', 'Value'],
    [
      ['Total Tests', data.quality.qualityTests.length],
      ['Passed', data.quality.testsPassed],
      ['Failed', data.quality.testsFailed],
      ['Pending', data.quality.testsPending],
      ['Pass Rate', `${data.quality.passRate}%`],
    ],
    { columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } } }
  );

  if (data.quality.qualityTests.length > 0) {
    addTable(
      ['Date', 'Test Type', 'Location', 'Result', 'Spec Limit', 'Status'],
      data.quality.qualityTests.slice(0, 30).map(t => [
        t.test_date, t.test_type, t.location || '—', t.result_value || '—', t.spec_limit || '—', t.result_status
      ])
    );
  }

  // 8. MATERIALS
  sectionTitle('Materials Received', 8);
  if (data.materials.length > 0) {
    addTable(
      ['Material', 'Description', 'Quantity', 'Unit', 'Source', 'Date'],
      data.materials.map(m => [
        m.material_type, m.description || '—', fmtNum(m.quantity), m.unit, m.source || '—', m.received_date
      ])
    );
  } else {
    addText('No materials received during this period.');
  }

  // 9. STRUCTURES
  sectionTitle('Structures Progress', 9);
  if (data.structures.structProgress.length > 0) {
    addTable(
      ['Structure', 'Type', 'Chainage', 'Stage', 'Status', 'Concrete (m³)', 'Rebar (kg)'],
      data.structures.structProgress.map(s => [
        s.structure?.structure_ref || '—', s.structure?.structure_type || '—',
        s.structure?.chainage || '—', s.stage, s.status,
        fmtNum(s.concrete_volume_m3), fmtNum(s.rebar_kg)
      ])
    );
  } else {
    addText('No structures progress recorded for this month.');
  }

  // 10. SITE ISSUES
  sectionTitle('Site Issues', 10);
  addTable(
    ['Parameter', 'Value'],
    [
      ['Issues Raised This Month', data.issues.issues.length],
      ['Open', data.issues.issuesOpened],
      ['Closed / Resolved', data.issues.issuesClosed],
      ['Critical / High Severity', data.issues.criticalIssues],
    ],
    { columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } } }
  );
  if (data.issues.issues.length > 0) {
    addTable(
      ['Date', 'Title', 'Category', 'Severity', 'Status'],
      data.issues.issues.map(i => [
        i.reported_date, i.title, i.category, i.severity, i.status
      ])
    );
  }

  // 11. SITE INSTRUCTIONS
  sectionTitle('Site Instructions', 11);
  if (data.instructions.length > 0) {
    addTable(
      ['SI No.', 'Type', 'Subject', 'Status'],
      data.instructions.map(si => [
        si.instruction_no, si.instruction_type?.replace(/_/g, ' '), si.subject, si.status
      ])
    );
  } else {
    addText('No site instructions issued during this period.');
  }

  // 12. VARIATION ORDERS
  sectionTitle('Variation Orders', 12);
  if (data.variationOrders.variationOrders.length > 0) {
    addTable(
      ['VO No.', 'Title', 'Type', 'Amount (KES)', 'Time Impact (days)', 'Status'],
      data.variationOrders.variationOrders.map(v => [
        v.vo_number, v.title, v.vo_type, fmtNum(v.approved_amount || v.estimated_amount),
        v.time_impact_days, v.status
      ])
    );
    addText(`Total VO value: ${fmtCurrency(data.variationOrders.totalVOAmount)}`);
  } else {
    addText('No variation orders on record.');
  }

  // 13. HEALTH & SAFETY
  sectionTitle('Health & Safety', 13);
  addText(data.narrative.hse_narrative || `${data.safety.safetyIncidents.length} incidents recorded. LTIs: ${data.safety.ltiCount}. Days lost: ${data.safety.totalDaysLost}.`);
  addTable(
    ['Parameter', 'Value'],
    [
      ['Total Incidents', data.safety.safetyIncidents.length],
      ['Near Misses', data.safety.nearMisses],
      ['Lost Time Injuries (LTI)', data.safety.ltiCount],
      ['Days Lost', data.safety.totalDaysLost],
    ],
    { columnStyles: { 0: { fontStyle: 'bold', cellWidth: 60 } } }
  );

  // 14. PHOTOS
  sectionTitle('Site Photographs', 14);
  addText(`${data.photos.length} photographs captured during the reporting period.`);
  if (data.photos.length > 0) {
    addTable(
      ['Date', 'Category', 'Caption', 'Chainage'],
      data.photos.slice(0, 20).map(ph => [
        ph.photo_date, ph.category?.replace(/_/g, ' '), ph.caption || '—', ph.chainage || '—'
      ])
    );
  }

  // 15. UPCOMING MONTH
  sectionTitle('Programme for Next Month', 15);
  addText(data.narrative.upcoming_month_plan || 'No forward plan provided. Please add narrative via the Monthly Report editor.');

  // 16. CRITICAL ISSUES & RECOMMENDATIONS
  sectionTitle('Critical Issues & Recommendations', 16);
  addText(data.narrative.critical_issues || 'No critical issues flagged.');
  if (data.narrative.recommendations) {
    checkPage(15);
    doc.setFont('helvetica', 'bold');
    addText('Recommendations:');
    doc.setFont('helvetica', 'normal');
    addText(data.narrative.recommendations);
  }

  // Add footers
  addPageFooter();

  return doc;
}
